"""Add is_admin field

Revision ID: 547899a136a1
Revises: 41ce64fac109
Create Date: 2021-03-06 20:00:43.277946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547899a136a1'
down_revision = '41ce64fac109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
